name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      user: action/checkout@v2

    - name: Setup MSBuild
      user: microsofr/setup-msbuild@1.0.1

    - name: Build
      run: msbuild /p:Configuration=Release
    
    - name: Run Tests
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
